# Part 1 - Installing **NumPY** 
---
Install using terminal:
`pip install numpy`


## Import Numpy

In [2]:
import numpy as np

# Part 2 - What is an array ?
---
An array is similar to a List.

BUT:
- faster
- more powerful
- optimized for numerical operations

In [3]:
# Numpy Array Example
import numpy as np

numbers = np.array([1, 2, 3, 4])

print(numbers)

[1 2 3 4]


## Difference b/w List and Array
| Feature | List | NumPY Array |
| --- | --- | --- |
| Speed | Slower | Faster |
| Numerical operations | Limited | Advanced |
| Memory efficiency | Lower | Higher |
| Data Analysis use | Basic | Professional |

# Part 3 - Creating Arrays
---

In [2]:
# Integer array
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr)

[1 2 3 4]


In [3]:
# Float array
arr = np.array([1.5, 2.5, 3.5])

print(arr)

[1.5 2.5 3.5]


In [4]:
# Mixed
arr = np.array([1, 2.5, 3])
print(arr)

[1.  2.5 3. ]


# Part 4 - Array Attributes
---

In [5]:
# Shape
arr = np.array([1, 2, 3])
                            # 3 elements,1-dimensional array
print(arr.shape)

(3,)


In [6]:
# data type 
print(arr.dtype)

int64


In [11]:
# Size
print(arr.size)

3


# Part 5 - Array Indexing
---
similar to list


In [13]:
arr = np.array([10, 20, 30, 40])

print(arr[3])

40


# Part 6 - Array Slicing

In [7]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[2:])    #include : start index  and exclude : end index

[30 40 50]


# Part 7 - Array Operations
---
Unlike lists, array allow direct mathematical operations 

In [9]:
# Example - Addition
arr = np.array([1, 2, 3])

print(arr + 5) # numpy adds 5 to every element

[6 7 8]


In [13]:
# Example - Multiplication
arr = np.array([2,4,6])

print(arr * 3)

[ 6 12 18]


# Part 8 - Array Arithmetic 
---

In [20]:
# Addition b/t arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)

[5 7 9]


In [23]:
# Multiplication
print(a * b)

[ 4 10 18]


# Part 9-Aggregation Functions
---

In [24]:
# Sum
sales = np.array([1000, 2000, 3000])

print(sales.sum())

6000


In [25]:
# Mean
sales = np.array([1000, 2000, 3000])

print(sales.mean())

2000.0


In [26]:
# max 
sales = np.array([1000, 2000, 3000])

print(sales.max())

3000


In [27]:
# min
sales = np.array([1000, 2000, 3000])

print(sales.min())

1000


In [28]:
# standard deviation
sales = np.array([1000, 2000, 3000])

print(sales.std())

816.496580927726


# Part 10 - Creating special arrays
---

In [31]:
# zero arrays
arr = np.zeros(5)

print(arr)

[0. 0. 0. 0. 0.]


In [32]:
# ones array
arr = np.ones(5)

print(arr)

[1. 1. 1. 1. 1.]


In [37]:
# range array
arr = np.arange(1, 11, 2)

print(arr)

[1 3 5 7 9]


# Part 11 - Multi - Dimensional Arrays
---
NumPY supports table/matrices 

In [38]:
# 2 - D Array example
data = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(data)

[[1 2 3]
 [4 5 6]]


In [39]:
# shape
print(data.shape)

(2, 3)


Meaning:
- 2 rows
- 3 columns

# Part 12 - Reshaping Arrays
---

In [46]:
# Example
arr = np.arange(1, 7)

new_arr = arr.reshape(2, 3)

print(new_arr)

[[1 2 3]
 [4 5 6]]


## Understanding
converted:
- 1-D array
    → into
- 2-D array

# Part 13 - Random Numbers
---
Useful in Simulation and ML

In [51]:
# example
arr = np.random.randint(1, 100, 5)

print(arr)

[95  4 75 81 52]


## Understanding
```python
randint(start, end, count)
```

# Real Data Analyst Uses of NumPy

### NumPy is used for:

- Numerical calculations
- Matrix operations
- Machine learning preprocessing
- Statistical analysis
- Feature engineering
- Financial modeling